- name: Provide infrastructure
  terraform:
    project_path: "{{ project_dir }}"
    state: "{{ state }}"
    force_init: true
    variables:
       count_vms: "{{ count_vms }}"
       default_user_name: "{{ default_user_name }}"
       disk_default_size: "{{ disk_default_size }}"
       environment: "{{ gcpenvironment }}"
       projectname: "{{ projectname }}"
  register: command_output
- debug: msg="{{command_output.stdout}}"
- debug: msg="{{command_output.command}}"
- debug: msg="{{command_output.outputs}}"
