- name: Provide infrastructure
  terraform:
    project_path: '/data/gcp-terraform/'
    state: "{{ state }}"
    force_init: true
    variables:
       count_vms: 1
       default_user_name: "<<your local user for using gcloud cli>>"
       disk_default_size: 20
       environment: "dev"
       projectname: "<<your google cloud project name>>"
  register: command_output
- debug: msg="{{command_output.stdout}}"
- debug: msg="{{command_output.command}}"
- debug: msg="{{command_output.outputs}}"
